id: PCC725946
initial_creation_type: ocr
source_metadata:
  volumes:
    9e9cab1b6ffb480ba66eb16a3b837176:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: སངས་རྒྱས་ཡོངས་སུ་མྱ་ངན་ལས་འདས་པ་ལ་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
